### ISSUE TITLE
LM request.temperature fail with error: TypeError: generate_step() got an unexpected keyword argument 'temp'

### ISSUE THREAD

**Issue by ami-navon** [arcee-ai/fastmlx#44]
LM request.temperature fail with error: 

TypeError: generate_step() got an unexpected keyword argument 'temp'

$ uvicorn fastmlx:app --workers 4

Traceback (most recent call last):
  File "/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/lib/python3.12/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/lib/python3.12/site-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/lib/python3.12/site-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/fastmlx/fastmlx.py", line 214, in chat_completion
    output = lm_generate(
             ^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/fastmlx/utils.py", line 369, in lm_generate
    generate_step(prompt_tokens, model, **kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: generate_step() got an unexpected keyword argument 'temp'

# API call:
import requests
import json
model_name_t= "mlx-community/gemma-2-9b-it-4bit"
url = "http://localhost:8000/v1/chat/completions"
headers = {"Content-Type": "application/json"}
prompt_t="capital of france"
data = {"model": model_name_t, "messages": [{"role": "user", "content": prompt_t}],"max_tokens": 100}
response = requests.post(url, headers=headers, data=json.dumps(data))
print(response.json())

# lib versions
fastmlx==0.2.1
mlx==0.23.2
mlx-lm==0.21.5
mlx-vlm==0.1.16

# The relevant line for lm_generate(..)
# From fastmlx/fastmlx.py , line 214:
             output = lm_generate(
                model,
                tokenizer,
                prompt,
                request.max_tokens,
                temp=request.temperature, # <= temp
                stop_words=stop_words,
            )

**Comment by qnguyen3** [comment]
@ami-navon i fixed it with the latest PR, can you try to pull and run your script again?

**Comment by markus022** [comment]
Hi,

Just wanted to confirm that this issue still exists — I installed the FastMLX server today (latest version as of now) and had to manually patch the temperature handling to get it working properly.

Besides that, everything works great — awesome job on the project! 🚀👏

Thanks!
